# Copyright 2026 The Cocomhub Authors. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false
  staticcheck:
    checks: ["all", "-SA6002"]

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - linters:
        - errcheck
      source: "Encode"
    - linters:
        - errcheck
      source: "w.Write"
    - linters:
        - errcheck
      source: "UpdateStatus"
    - linters:
        - errcheck
      source: "os\\."
    - linters:
        - errcheck
      source: "io\\.Copy"
    - linters:
        - errcheck
      source: "\\.Set\\("
    - linters:
        - errcheck
      source: "SetConcurrency|SetRefreshInterval"
    - linters:
        - errcheck
      source: "\\.Write\\("
    - path: pkg\\dlcore\\client\\.go
      linters:
        - staticcheck
    - path: api\\server\\.go
      linters:
        - staticcheck
    - path: task\\vikacg\\task\\.go
      linters:
        - staticcheck
    - path: manager\\manager\\.go
      linters:
        - gosimple

run:
  timeout: 3m
  go: "1.22"