# Copyright 2026 The Cocomhub Authors. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
  disable:
    - scopelint
    - maligned

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
  staticcheck:
    checks: ["all"]

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 3m
  go: "1.22"