server:
  http_port: 8080
  work_dir: ./build/test
  lock_file: ./build/test/download-manager.lock
  scraper_path: ./build/bin/scraper_get
  ui_defaults:
    default_save_dir: ./downloads
    window_width: 1200
    window_height: 800
    diff_side_by_side: false
    diff_ignore_ws: false
    diff_ignore_comment: false
    status_style: overlay
log:
  level: debug
  filename: ./build/test/logs/app.log
  max_size: 10
  max_backups: 3
  max_age: 28
  console: true
  compress: true
mongo:
  - name: suixi-mini
    uri: mongodb://root:root123@suixi-mini.local:27017/download_manager?authSource=admin
downloader:
  type: native
  global_concurrent: 1
  max_retries: 3
  log_dir: ./build/test/logs/downloader
  force_proxy: false
  proxies:
    - http://129.226.212.209:18080
    - http://43.159.49.114:18080
task_scan:
  disable: false
  interval: 10
tasks:
  - id: task-file-001
    type: simple_url_list
    save_dir: ./build/test/downloads/task1
    storage:
      type: file
      config:
        path: ./build/test/downloads/task1/status.json
        save_interval: "2"
    extra:
      urls:
        - https://www.baidu.com/robots.txt
        - https://www.bing.com/robots.txt
  - id: task-mongo-001
    type: simple_url_list
    save_dir: ./build/test/downloads/task2
    storage:
      type: mongo
      config:
        collection: task_mongo_001
        database: download_manager
        source: suixi-mini
    extra:
      urls:
        - https://www.bing.com/robots.txt
  - id: task-vikacg-001
    type: vikacg
    save_dir: ./build/test/downloads/vikacg
    storage:
      type: file
      config:
        path: ./build/test/downloads/vikacg/status.json
        save_interval: "2"
    extra:
      max_concurrent: 2
      urls:
        - https://www.vikacg.com/p/511657
  - id: task-hanime-001
    type: hanime
    save_dir: ./build/test/downloads/hanime
    storage:
      type: file
      config:
        path: ./build/test/downloads/hanime/status.json
        save_interval: "2"
    extra:
      keyword: 裏番
      max_concurrent: 1
      refresh_interval: 3600
      path_strategy: first_fixed
      save_dir_add_keyword: false
